version: '3'

services:

  mysql-development:
    image: mysql:8.0.17
    environment:
      MYSQL_ROOT_PASSWORD: testing123
      MYSQL_DATABASE: todoApi
    ports:
      - "3308:3306"

    volumes:
      - ./init:/docker-entrypoint-initdb.d
